//
//  NSTouchBarItemIdentifierDeckAddCardOptionType+BlizzardHSAPIOptionType.h
//  StoneNamu
//
//  Created by Jinwoo Kim on 12/3/21.
//

#import <Cocoa/Cocoa.h>
#import <StoneNamuCore/StoneNamuCore.h>

NS_ASSUME_NONNULL_BEGIN

static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeSet = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeSet";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeClass = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeClass";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeManaCost = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeManaCost";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeAttack = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeAttack";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeHealth = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeHealth";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeCollecticle = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeCollecticle";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeRarity = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeRarity";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeType = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeType";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeMinionType = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeMinionType";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeSchoolSpell = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeSchoolSpell";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeKeyword = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeKeyword";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeGameMode = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeGameMode";
static NSTouchBarItemIdentifier const NSTouchBarItemIdentifierDeckAddCardOptionTypeSort = @"NSTouchBarItemIdentifierDeckAddCardOptionTypeSort";

NSArray<NSTouchBarItemIdentifier> * allNSTouchBarItemIdentifierDeckAddCardOptionTypes(void);
NSTouchBarItemIdentifier NSTouchBarItemIdentifierDeckAddCardOptionTypeFromBlizzardHSAPIOptionType(BlizzardHSAPIOptionType type);
BlizzardHSAPIOptionType BlizzardHSAPIOptionTypeFromNSTouchBarItemIdentifierDeckAddCardOptionType(NSTouchBarItemIdentifier itemIdentifier);

NS_ASSUME_NONNULL_END
