//
//  NSUserInterfaceItemIdentifierDeckAddCardOptionType+BlizzardHSAPIOption.h
//  StoneNamu
//
//  Created by Jinwoo Kim on 12/3/21.
//

#import <Cocoa/Cocoa.h>
#import <StoneNamuCore/StoneNamuCore.h>

NS_ASSUME_NONNULL_BEGIN

static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeTextFilter = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeTextFilter";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSet = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSet";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeClass = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeClass";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeManaCost = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeManaCost";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeAttack = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeAttack";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeHealth = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeHealth";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeCollectible = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeCollectible";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeRarity = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeRarity";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeType = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeMinionType = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeMinionType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSpellSchool = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSpellSchool";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeKeyword = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeKeyword";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeGameMode = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeGameMode";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSort = @"NSUserInterfaceItemIdentifierDeckAddCardOptionTypeSort";

NSArray<NSUserInterfaceItemIdentifier> *allNSUserInterfaceItemIdentifierDeckAddCardOptionType(void);
NSUserInterfaceItemIdentifier NSUserInterfaceItemIdentifierDeckAddCardOptionTypeFromBlizzardHSAPIOptionType(BlizzardHSAPIOptionType type);
BlizzardHSAPIOptionType BlizzardHSAPIOptionTypeFromNSUserInterfaceItemIdentifierDeckAddCardOptionType(NSUserInterfaceItemIdentifier item);

NS_ASSUME_NONNULL_END
