//
//  NSUserInterfaceItemIdentifierCardOptionType+BlizzardHSAPIOption.h
//  StoneNamu
//
//  Created by Jinwoo Kim on 11/9/21.
//

#import <Cocoa/Cocoa.h>
#import <StoneNamuCore/StoneNamuCore.h>

static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeTextFilter = @"NSUserInterfaceItemIdentifierCardOptionTypeTextFilter";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeSet = @"NSUserInterfaceItemIdentifierCardOptionTypeSet";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeClass = @"NSUserInterfaceItemIdentifierCardOptionTypeClass";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeManaCost = @"NSUserInterfaceItemIdentifierCardOptionTypeManaCost";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeAttack = @"NSUserInterfaceItemIdentifierCardOptionTypeAttack";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeHealth = @"NSUserInterfaceItemIdentifierCardOptionTypeHealth";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeCollectible = @"NSUserInterfaceItemIdentifierCardOptionTypeCollectible";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeRarity = @"NSUserInterfaceItemIdentifierCardOptionTypeRarity";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeType = @"NSUserInterfaceItemIdentifierCardOptionTypeType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeMinionType = @"NSUserInterfaceItemIdentifierCardOptionTypeMinionType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeSpellSchool = @"NSUserInterfaceItemIdentifierCardOptionTypeSpellSchool";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeKeyword = @"NSUserInterfaceItemIdentifierCardOptionTypeKeyword";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeGameMode = @"NSUserInterfaceItemIdentifierCardOptionTypeGameMode";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionTypeSort = @"NSUserInterfaceItemIdentifierCardOptionTypeSort";

NSArray<NSUserInterfaceItemIdentifier> *allNSUserInterfaceItemIdentifierCardOptionTypes(void);
NSUserInterfaceItemIdentifier NSUserInterfaceItemIdentifierCardOptionTypeFromBlizzardHSAPIOptionType(BlizzardHSAPIOptionType type);
BlizzardHSAPIOptionType BlizzardHSAPIOptionTypeFromNSUserInterfaceItemIdentifierCardOptionType(NSUserInterfaceItemIdentifier item);
