//
//  NSUserInterfaceItemIdentifierCardOptions+BlizzardHSAPIOption.h
//  StoneNamu
//
//  Created by Jinwoo Kim on 11/9/21.
//

#import <Cocoa/Cocoa.h>
#import <StoneNamuCore/StoneNamuCore.h>

static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsTextFilter = @"NSUserInterfaceItemIdentifierCardOptionsTextFilter";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsSet = @"NSUserInterfaceItemIdentifierCardOptionsSet";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsClass = @"NSUserInterfaceItemIdentifierCardOptionsClass";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsManaCost = @"NSUserInterfaceItemIdentifierCardOptionsManaCost";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsAttack = @"NSUserInterfaceItemIdentifierCardOptionsAttack";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsHealth = @"NSUserInterfaceItemIdentifierCardOptionsHealth";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsCollectible = @"NSUserInterfaceItemIdentifierCardOptionsCollectible";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsRarity = @"NSUserInterfaceItemIdentifierCardOptionsRarity";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsType = @"NSUserInterfaceItemIdentifierCardOptionsType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsMinionType = @"NSUserInterfaceItemIdentifierCardOptionsMinionType";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsSpellSchool = @"NSUserInterfaceItemIdentifierCardOptionsSpellSchool";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsKeyword = @"NSUserInterfaceItemIdentifierCardOptionsKeyword";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsGameMode = @"NSUserInterfaceItemIdentifierCardOptionsGameMode";
static NSUserInterfaceItemIdentifier const NSUserInterfaceItemIdentifierCardOptionsSort = @"NSUserInterfaceItemIdentifierCardOptionsSort";

NSArray<NSUserInterfaceItemIdentifier> *allNSUserInterfaceItemIdentifierCardOptions(void);
NSUserInterfaceItemIdentifier NSUserInterfaceItemIdentifierCardOptionsFromBlizzardHSAPIOptionType(BlizzardHSAPIOptionType type);
BlizzardHSAPIOptionType BlizzardHSAPIOptionTypeFromNSUserInterfaceItemIdentifierCardOptions(NSUserInterfaceItemIdentifier item);
